server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://mysql:3306/k3d_demo_schema  # url should be equal to mysql container name
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

