server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://mysql.mysql-ns:3306/k3d_demo_schema  # url: service-name.namespace:port
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka-ns:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable:
        auto:
          commit: false
    producer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka-ns:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

camel:
  springboot:
    name: web-app demo
  health:
    indicator:
      enabled: true
    check:
      indicator:
        enabled: false

elasticsearch:
  url: elasticsearch-es-http.elasticsearch-ns
  port: 9200
  username: elastic
  password: FM0xpqu4T7j7Zt7w17744QIR # change with: kubectl -n kube-elastic get secret elasticsearch-es-elastic-user -o go-template='{{.data.elastic | base64decode}}'
  key-store-file: "/tmp/elastic-certificates.p12"
  cert-file-password: ""
  index-name: customer

